### ISSUE TITLE
Notebook: Performing Retention Modeling yields error relating to the standard errors columns

### ISSUE THREAD

**Issue by BrianvantVeer** [GasChromatographyToolbox/RetentionParameterEstimator.jl#34]
When  using the Notebook, modeling does not work at this moment.

Steps to reproduce:
1. open the notebook in Pluto (https://github.com/GasChromatographyToolbox/RetentionParameterEstimator.jl/blob/main/notebooks/estimate_retention_parameters.jl)
2. Wait for the notebook to load.
3. Check if there are  measurements and compounds preselected, otherwise --> select them and click on 'submit'
4. Go to the "Select Mode" header and select one of the modes (either of the m1, m1a, m2 give the error)
5. Click on submit and see the resulting error (see error message at the end of this description)

**Expected Behavior**
The dataframe  of the model should show

**Expected Bug**
There is probably a missing optional variable in one of the function definitions, that is still being used as input for the function. This is  most likely because the  notebook uses the package *RetentionParameterEstimator v0.1.8*

Error Message
```
MethodError: no method matching check_measurement(::Tuple{GasChromatographySimulator.Column, Vector{GasChromatographySimulator.Program}, DataFrames.DataFrame, Vector{String}, String, String}, ::@NamedTuple{L::Float64, d::Float64}; min_th::Float64, loss_th::Float64, se_col::Bool)

Closest candidates are:

check_measurement(::Any, ::Any; min_th, loss_th) got unsupported keyword argument "se_col"

@ RetentionParameterEstimator C:\Users\...\.julia\packages\RetentionParameterEstimator\vk2Rk\src\Optimization.jl:393
```

**Comment by JanLeppert** [comment]
cosed by #36 and #38
